baseURL = 'https://closeroll.eu/'
languageCode = 'en-us'
title = 'Close Rol - Tutorials'

paginate = 4

[params]
  description = "Tutorials, Free Online Tutorials, Closeroll provides tutorials and interview questions of all technology like java tutorial, android, java frameworks, javascript, ajax, core java, sql, python, php, c language etc. for beginners and professionals."
  dateFormat = "Jan 2, 2006"
  keywords = "Closeroll,HTML, Python, CSS, SQL, JavaScript, How to, PHP, Java, C, C++, C#, jQuery, Bootstrap, Colors, W3.CSS, XML, MySQL, Icons, NodeJS, React, Graphics, Angular, R, AI, Git, Data Science, Code Game, Tutorials, Programming, Web Development, Training, Learning, Quiz, Exercises, Courses, Lessons, References, Examples, Learn to code, Source code, Demos, Tips, Website"
  title = 'Close Rol'
  

[taxonomies]
  category = "categories"
  author = "admin"
