baseURL = 'https://closeroll.eu/'
languageCode = 'en-us'
title = 'Close Rol - Tutorials'

paginate = 4

[params]
  description = "Tutorials, Free Online Tutorials, Closeroll provides tutorials and interview questions of all technology like java tutorial, android, java frameworks, javascript, ajax, core java, sql, python, php, c language etc. for beginners and professionals."
  dateFormat = "Jan 2, 2006"
  keywords = "Closeroll, java tutorial, core java tutorial, beginners, professionals"
  title = 'Close Rol'
  

[taxonomies]
  category = "categories"
  author = "admin"
