baseURL = 'https://abdelhadi-haddadi.github.io/hugo-blog-app/'
languageCode = 'en-us'
title = 'dev blog'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
