baseURL = 'https://closeroll.eu/'
languageCode = 'en-us'
title = 'Close Rol - Tutorials'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"
  keywords = "Closeroll, java tutorial, core java tutorial, beginners, professionals"

[taxonomies]
  category = "categories"
  author = "admin"
