baseURL = 'https://closeroll.eu/'
languageCode = 'en-us'
title = 'Close Rol - Tutorials'

paginate = 10

[params]
  description = "in CloseRoll Well organized and easy to understand Web building tutorials with lots of examples of how to use HTML, CSS, JavaScript, SQL, Python, PHP, Bootstrap, Java, XML , ML , AI and more"
  dateFormat = "Jan 2, 2006"
  keywords = "Closeroll,HTML, Python, CSS, SQL, JavaScript, How to, PHP, Java, C, C++, C#, jQuery, Bootstrap, Colors, W3.CSS, XML, MySQL, Icons, NodeJS, React, Graphics, Angular, R, AI, Git, Data Science, Code Game, Tutorials, Programming, Web Development, Training, Learning, Quiz, Exercises, Courses, Lessons, References, Examples, Learn to code, Source code, Demos, Tips, Website"
  title = 'Close Rol'
  

[taxonomies]
  category = "categories"
  author = "admin"
